services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_news_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL="postgresql://postgres.engepyysrjkmhxkumyit:{supabase_pass}@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres"
    networks:
      - app_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 75s
      timeout: 10s
      retries: 3

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.Scheduler
    container_name: ai_news_scheduler
    command: python -m scheduler.sch
    env_file: .env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure
    environment:
      - DATABASE_URL="postgresql://postgres.engepyysrjkmhxkumyit:{supabase_pass}@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres"

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai_news_frontend 
    command: streamlit run main.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:
    driver: bridge 
    


    